apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service_type }}
  selector:
    appName: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }} #service port
      targetPort: {{ .Values.appPort }} #target port
